const usernames = [
    "laura palmer",
    'peterpan',
    'wendydarling',
    'mickeymouse',
    'donaldduck',
    'minniemouse',
    'goofy',
    'plutodog',
    'arielmermaid',
    'aladdin',
    'jasmine',
    'simba',
    'scarlion',
    'timonmeerkat',
    'pumbawarthog',
    'hercules',
    'megara',
    'tarzan',
    'janeporter',
    'mulan',
    'shang',
    'kuzco',
    'malina',
    'homer',
    'marge',
    'bart',
    'lisa',
    'maggie',
    'nedflanders',
    'maudeszyslak',
    'barneygumble',
    'lenny',
    'carlsquire',
    'apu',
    'manjulanahasapeemapetilon',
    'seymourskinner',
    'edna',
    'milhouse',
    'martinprince',
    'nelsonmuntz',
    'ralphwiggum',
    'kenny',
    'stanmarsh',
    'kylebroflovski',
    'paulabennett',
    'tomcolicchio',
    'padmalakshmi',
    'gailsimmons',
    'richardblais',
    'carlahall',
    'michaelvoltaggio',
    'bryanvoltaggio'];

    const thoughtsArray = [
        "I love cigars. They remind me that life is short, and sometimes it's okay to just sit back and enjoy the simple things. - Norm Macdonald",
        "Trees are amazing. They're like nature's skyscrapers, but they don't block your view of the stars. - Rodney Dangerfield",
        "Dogs are the best. They don't care if you're rich or poor, they just want to play and love you. If only people were that simple. - Kermit the Frog",
        "Cigars are a lot like life. You have to savor the good moments, but be prepared for the bitter ones. - Norm Macdonald",
        "Trees are like the lungs of the planet. They take in carbon dioxide and give out oxygen. We could learn a thing or two from them. - Rodney Dangerfield",
        "Dogs are like therapists. They listen to your problems without judging you, and they always have a wagging tail and a wet nose to make you feel better. - Kermit the Frog",
        "If you're having a bad day, just light up a cigar and enjoy the moment. It won't solve your problems, but it will make them seem a little less important. - Norm Macdonald",
        "Trees are survivors. They weather storms and droughts and still manage to stand tall and proud. Maybe we can learn a little something about resilience from them. - Rodney Dangerfield",
        "Dogs are like little rays of sunshine. They brighten up your day and make everything better with just a wag of their tail. - Kermit the Frog",
        "A cigar is a reminder that sometimes the best things in life are slow and deliberate. You can't rush a good cigar, and you can't rush a good life. - Norm Macdonald",
        "Trees are like history books. They've been around for centuries, watching the world change around them. If only they could talk, think of the stories they could tell. - Rodney Dangerfield",
        "Dogs are like detectives. They sniff out the good in people and help us see the world in a better light. - Kermit the Frog",
        "A good cigar is like a good friend. They're always there for you, they make you feel good, and they never judge you. - Norm Macdonald",
        "Trees are like works of art. They come in all shapes and sizes, and each one is unique and beautiful in its own way. - Rodney Dangerfield",
        "Dogs are like family. They're always there for you, they love you unconditionally, and they make life worth living. - Kermit the Frog",
        "Sometimes a cigar is just a cigar. But other times, it's a reminder to slow down, take a breath, and enjoy the simple things in life. - Norm Macdonald",
        "Trees are like old friends. They may have a few wrinkles and a few scars, but they're always there for you, and they never forget the good times. - Rodney Dangerfield",
        "Dogs are like little miracles. They can turn the worst day into the best day with just a lick and a cuddle. - Kermit the Frog",
        "A cigar is a celebration of life. It's a reminder that every day is a gift, and that sometimes the best way to celebrate is to sit back, relax, and enjoy a good smoke. - Norm Macdonald",
        "Trees are like anchors. They keep us grounded, they give us shade and shelter, and they remind us that sometimes the best things in life are the simplest. - Rodney Danger"];

        const getRandomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

        const getRandomUser = () => {
            return getRandomItem(usernames);
        }

         module.exports = {usernames, thoughtsArray, getRandomItem, getRandomUser};